/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen_final;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NaniXC7
 */
public class ordenes extends javax.swing.JFrame {
    
    public static String nom;
    public static int contador = 0;

    /**
     * Creates new form ordenes
     */
    public ordenes() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        lista.addItem("Seleccionar");
        lista.addItem("Guatemala");
        lista.addItem("El Progreso");
        lista.addItem("Jalapa"); 
        
        pizzas logica = new pizzas();
        
        DefaultTableModel modelo = logica.mostrarordenes();
        
        ordenes.setModel(modelo);
        
    }
    
    public String [] pizzasj(String pizzasj){
    
        String [] datosj = new String[Examen_Final.nombresj.size()];
        
        if(pizzasj.equals("Jalapa")){
        
            for (int i = 0; i < Examen_Final.nombresj.size(); i++) {
                
                datosj[i] = Examen_Final.nombresj.get(i);
            
            }
        
        }
        
        return datosj;
    
    }
    
    public String [] pizzasep(String pizzasep){
    
        String [] datosep = new String[Examen_Final.nombresep.size()];
        
        if(pizzasep.equals("El Progreso")){
        
            for (int i = 0; i < Examen_Final.nombresep.size(); i++) {
                
                datosep[i] = Examen_Final.nombresep.get(i);
            
            }
        
        }
        
        return datosep;
    
    }
    
    public String [] pizzasg(String pizzasg){
    
        String [] datosg = new String[Examen_Final.nombresg.size()];
        
        if(pizzasg.equals("Guatemala")){
        
            for (int i = 0; i < Examen_Final.nombresg.size(); i++) {
                
                datosg[i] = Examen_Final.nombresg.get(i);
            
            }
        
        }
        
        return datosg;
    
    }
    
    public String [] vacio(String vacio){
    
        String [] datovacio = new String[1];
        
        datovacio[0] = "";
        
        return datovacio;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        selectedpizzas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        precio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrip = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordenes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("ORDENES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Sucursal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 104, -1, -1));

        lista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaItemStateChanged(evt);
            }
        });
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });
        getContentPane().add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 102, 95, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Pizza");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        selectedpizzas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectedpizzasItemStateChanged(evt);
            }
        });
        selectedpizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedpizzasActionPerformed(evt);
            }
        });
        getContentPane().add(selectedpizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 72, -1));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        precio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        precio.setText("Precio");
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        descrip.setColumns(20);
        descrip.setRows(5);
        jScrollPane1.setViewportView(descrip);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 195, 290, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Descripcion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Q.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jButton2.setText("Ordenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        ordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ordenes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 311, 390, 109));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaActionPerformed

    private void listaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaItemStateChanged
        
        if(evt.getStateChange() == ItemEvent.SELECTED){
        
            if(this.lista.getSelectedIndex() == 0){
            
                this.selectedpizzas.setModel(new DefaultComboBoxModel(this.vacio(this.lista.getSelectedItem().toString())));
                descrip.setText("");
                precio.setText("Precio");
            
            }else if(this.lista.getSelectedIndex() == 1){
                
                this.selectedpizzas.setModel(new DefaultComboBoxModel(this.pizzasg(this.lista.getSelectedItem().toString())));
                descrip.setText("");
                precio.setText("Precio");
                
            }else if(this.lista.getSelectedIndex() == 2){
            
                this.selectedpizzas.setModel(new DefaultComboBoxModel(this.pizzasep(this.lista.getSelectedItem().toString())));
                descrip.setText("");
                precio.setText("Precio");
                
            }else if(this.lista.getSelectedIndex() == 3){
            
                this.selectedpizzas.setModel(new DefaultComboBoxModel(this.pizzasj(this.lista.getSelectedItem().toString())));
                descrip.setText("");
                precio.setText("Precio");
                
            }
        
        }
        
            


        
        
    }//GEN-LAST:event_listaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        index c = new index();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectedpizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedpizzasActionPerformed
        
        
        
    }//GEN-LAST:event_selectedpizzasActionPerformed

    private void selectedpizzasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectedpizzasItemStateChanged
        if(this.lista.getSelectedIndex() == 0){
            
            this.selectedpizzas.setModel(new DefaultComboBoxModel(this.vacio(this.lista.getSelectedItem().toString())));
            
        }else if(this.selectedpizzas.getSelectedIndex() == 0){
            
            descrip.setText("");
            precio.setText("Precio");
            
        }else if(this.lista.getSelectedIndex() == 1){
            
            if(this.selectedpizzas.getSelectedIndex() > 0){
            
                String buscar = (String) selectedpizzas.getSelectedItem();
            
                for (int i = 0; i < Examen_Final.nombresg.size(); i++) {
                
                    if(buscar.equals(Examen_Final.nombresg.get(i))){
                
                        descrip.setText(Examen_Final.descripg.get(i-1));
                        precio.setText(Examen_Final.precig.get(i-1)+".00");
                    
                    }
                
                }
            
            }
  
        }else if(this.lista.getSelectedIndex() == 2){
            
            if(this.selectedpizzas.getSelectedIndex() > 0){
            
                String buscar = (String) selectedpizzas.getSelectedItem();
            
                for (int i = 0; i < Examen_Final.nombresep.size(); i++) {
                
                    if(buscar.equals(Examen_Final.nombresep.get(i))){
                
                        descrip.setText(Examen_Final.descripep.get(i-1));
                        precio.setText(Examen_Final.preciep.get(i-1)+".00");
                    
                    }
                
                }
            
            }
  
        }else if(this.lista.getSelectedIndex() == 3){
            
            if(this.selectedpizzas.getSelectedIndex() > 0){
            
                String buscar = (String) selectedpizzas.getSelectedItem();
            
                for (int i = 0; i < Examen_Final.nombresj.size(); i++) {
                
                    if(buscar.equals(Examen_Final.nombresj.get(i))){
                
                        descrip.setText(Examen_Final.descripj.get(i-1));
                        precio.setText(Examen_Final.precij.get(i-1)+".00");
                    
                    }
                
                }
            
            }
  
        }
    }//GEN-LAST:event_selectedpizzasItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(this.lista.getSelectedIndex() == 0){
        
            JOptionPane.showMessageDialog(null, "Debe elegir una sucursal");
        
        }else if(this.selectedpizzas.getSelectedIndex() == 0){
        
            JOptionPane.showMessageDialog(null, "Debe elegir una pizza");
        
        }else{
        
            String sucursal = "", pizza = "";
            
            sucursal = (String) lista.getSelectedItem();
            pizza = (String) selectedpizzas.getSelectedItem();
            
            contador++;
            
            Examen_Final.con.add(contador);
            Examen_Final.nombres.add(pizza);
            Examen_Final.descrip.add(descrip.getText());
            Examen_Final.suc.add(sucursal);
            
            
            
            pizzas logica = new pizzas();
        
            DefaultTableModel modelo = logica.mostrarordenes();
        
            ordenes.setModel(modelo);
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ordenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descrip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTable ordenes;
    private javax.swing.JLabel precio;
    private javax.swing.JComboBox<String> selectedpizzas;
    // End of variables declaration//GEN-END:variables
}
