/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_final_necflis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NaniXC7
 */
public class Seleccion_Peli extends javax.swing.JFrame {
    
    public static String nombre_peli;

    /**
     * Creates new form Seleccion_Peli
     */
    public Seleccion_Peli() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.setTitle("Seleccion de Pelíocula/Serie");

        
        extraccion_pelis logica = new extraccion_pelis();
        
        DefaultTableModel modelo = logica.mostrarClientes();
        
        tbl_pelis.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pelis = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_pelis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pelis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_pelis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pelisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pelis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 375, 160));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_final_necflis/imgenes/necflis new.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 110, 50));

        btn5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_final_necflis/imgenes/icons8_cancel_32px.png"))); // NOI18N
        btn5.setText("Cancelar");
        btn5.setBorder(null);
        btn5.setContentAreaFilled(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusPainted(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setSelected(true);
        btn5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_final_necflis/imgenes/tablas.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_pelisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pelisMouseClicked
        
        String tip = "", pl_nueva = Seleccion_Cliente.pl_cliente;
        int seleccion = tbl_pelis.rowAtPoint(evt.getPoint());
        nombre_peli = pl_nueva + String.valueOf(tbl_pelis.getValueAt(seleccion, 1)) + "  ";
        Seleccion_Cliente.playlist_cliente += 1;
        tip = String.valueOf(tbl_pelis.getValueAt(seleccion, 2));

        try{

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/necflis", "root", "");
            PreparedStatement pst = cn.prepareStatement("UPDATE clientes SET ID='"+ Seleccion_Cliente.id_cliente +"',nombre='"+ Seleccion_Cliente.nombre_cliente +"',direccion='"+ Seleccion_Cliente.direccion_cliente +"',edad='"+ Seleccion_Cliente.edad_cliente +"',`playlist`='"+ Seleccion_Cliente.playlist_cliente +"',detalle_pl='"+ nombre_peli +"' WHERE ID="+Seleccion_Cliente.id_cliente);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "La " + tip.toLowerCase() + " se agregó correctamente :D");

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, "Error al agregar película :(");

        }

        new Seleccion_Cliente().setVisible(true);
        dispose();

    }//GEN-LAST:event_tbl_pelisMouseClicked

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        new Info_Cliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion_Peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion_Peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion_Peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion_Peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion_Peli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_pelis;
    // End of variables declaration//GEN-END:variables
}
